<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
$APPLICATION->IncludeComponent("bitrix:catalog", "catalog", Array(
	"IBLOCK_TYPE" => "1c_catalog",	// Тип инфоблока
		"IBLOCK_ID" => "35",	// Инфоблок
		"HIDE_NOT_AVAILABLE" => "N",	// Недоступные товары
		"BASKET_URL" => "/basket/",	// URL, ведущий на страницу с корзиной покупателя
		"ACTION_VARIABLE" => "action",	// Название переменной, в которой передается действие
		"PRODUCT_ID_VARIABLE" => "id",	// Название переменной, в которой передается код товара для покупки
		"SECTION_ID_VARIABLE" => "SECTION_ID",	// Название переменной, в которой передается код группы
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",	// Название переменной, в которой передается количество товара
		"PRODUCT_PROPS_VARIABLE" => "prop",	// Название переменной, в которой передаются характеристики товара
		"SEF_MODE" => "Y",	// Включить поддержку ЧПУ
		"SEF_FOLDER" => "/catalog/",	// Каталог ЧПУ (относительно корня сайта)
		"AJAX_MODE" => "N",	// Включить режим AJAX
		"AJAX_OPTION_JUMP" => "N",	// Включить прокрутку к началу компонента
		"AJAX_OPTION_STYLE" => "Y",	// Включить подгрузку стилей
		"AJAX_OPTION_HISTORY" => "Y",	// Включить эмуляцию навигации браузера
		"CACHE_TYPE" => "A",	// Тип кеширования
		"CACHE_TIME" => "3600000",	// Время кеширования (сек.)
		"CACHE_FILTER" => "Y",	// Кешировать при установленном фильтре
		"CACHE_GROUPS" => "Y",	// Учитывать права доступа
		"SET_TITLE" => "Y",	// Устанавливать заголовок страницы
		"SET_STATUS_404" => "Y",	// Устанавливать статус 404
		"USE_ELEMENT_COUNTER" => "Y",	// Использовать счетчик просмотров
		"USE_FILTER" => "Y",	// Показывать фильтр
		"FILTER_NAME" => "MAX_SMART_FILTER",	// Фильтр
		"FILTER_FIELD_CODE" => array(	// Поля
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(	// Свойства
			0 => "CML2_ARTICLE",
			1 => "IN_STOCK",
			2 => "",
		),
		"FILTER_PRICE_CODE" => array(	// Тип цены
			0 => "BASE",
		),
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "CML2_LINK",
			3 => "",
		),
		"USE_REVIEW" => "Y",	// Разрешить отзывы
		"MESSAGES_PER_PAGE" => "5",	// Количество сообщений на одной странице
		"USE_CAPTCHA" => "Y",	// Использовать CAPTCHA
		"REVIEW_AJAX_POST" => "Y",	// Использовать AJAX в диалогах
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",	// Путь относительно корня сайта к папке со смайлами
		"FORUM_ID" => "1",	// ID форума для отзывов
		"URL_TEMPLATES_READ" => "",	// Страница чтения темы (пусто - получить из настроек форума)
		"SHOW_LINK_TO_FORUM" => "Y",	// Показать ссылку на форум
		"POST_FIRST_MESSAGE" => "N",
		"USE_COMPARE" => "Y",	// Разрешить сравнение товаров
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",	// Уникальное имя для списка сравнения
		"COMPARE_FIELD_CODE" => array(	// Поля
			0 => "NAME",
			1 => "TAGS",
			2 => "SORT",
			3 => "PREVIEW_PICTURE",
			4 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "BRAND",
			1 => "CML2_ARTICLE",
			2 => "CML2_BASE_UNIT",
			3 => "PROP_2033",
			4 => "COLOR_REF2",
			5 => "PROP_159",
			6 => "PROP_2065",
			7 => "PROP_2052",
			8 => "PROP_2053",
			9 => "PROP_2083",
			10 => "PROP_2054",
			11 => "PROP_2017",
			12 => "PROP_2026",
			13 => "PROP_2027",
			14 => "PROP_2049",
			15 => "PROP_2044",
			16 => "PROP_162",
			17 => "CML2_MANUFACTURER",
			18 => "PROP_2055",
			19 => "PROP_2069",
			20 => "PROP_2062",
			21 => "PROP_2061",
			22 => "",
		),
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "ARTICLE",
			1 => "COLOR_REF",
			2 => "SIZES",
			3 => "VOLUME",
			4 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "shows",	// По какому полю сортируем элементы
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",	// Порядок сортировки элементов
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",	// Выводить список элементов инфоблока
		"PRICE_CODE" => array(	// Тип цены
			0 => "BASE",
			1 => "OPT",
			2 => "MSC",
			3 => "EKB",
			4 => "MAGNITOGORSK",
		),
		"USE_PRICE_COUNT" => "Y",	// Использовать вывод цен с диапазонами
		"SHOW_PRICE_COUNT" => "1",	// Выводить цены для количества
		"PRICE_VAT_INCLUDE" => "Y",	// Включать НДС в цену
		"PRICE_VAT_SHOW_VALUE" => "N",	// Отображать значение НДС
		"PRODUCT_PROPERTIES" => "",
		"USE_PRODUCT_QUANTITY" => "Y",	// Разрешить указание количества товара
		"CONVERT_CURRENCY" => "Y",	// Показывать цены в одной валюте
		"CURRENCY_ID" => "RUB",	// Валюта, в которую будут сконвертированы цены
		"OFFERS_CART_PROPERTIES" => "",
		"SHOW_TOP_ELEMENTS" => "Y",	// Выводить топ элементов
		"SECTION_COUNT_ELEMENTS" => "Y",	// Показывать количество элементов в разделе
		"SECTION_TOP_DEPTH" => "2",	// Максимальная отображаемая глубина разделов
		"SECTIONS_LIST_PREVIEW_PROPERTY" => "DESCRIPTION",	// Брать описание из
		"SHOW_SECTION_LIST_PICTURES" => "Y",	// Показывать картинки подразделов
		"PAGE_ELEMENT_COUNT" => "8",	// Количество элементов на странице
		"LINE_ELEMENT_COUNT" => "5",	// Количество элементов, выводимых в одной строке таблицы
		"ELEMENT_SORT_FIELD" => "sort",	// По какому полю сортируем товары в разделе
		"ELEMENT_SORT_ORDER" => "asc",	// Порядок сортировки товаров в разделе
		"ELEMENT_SORT_FIELD2" => "id",	// Поле для второй сортировки товаров в разделе
		"ELEMENT_SORT_ORDER2" => "asc",	// Порядок второй сортировки товаров в разделе
		"LIST_PROPERTY_CODE" => array(
			0 => "HIT",
			1 => "BRAND",
			2 => "CML2_ARTICLE",
			3 => "PROP_2104",
			4 => "CML2_ATTRIBUTES",
			5 => "FASADI",
			6 => "KORPUS",
			7 => "KOMPLECTACIA",
			8 => "DLINA",
			9 => "SHIRINA",
			10 => "VISOTA",
			11 => "GLUBINA",
			12 => "STOLESHNICA",
			13 => "ZERKALO",
			14 => "VISOTASIDENIA",
			15 => "TOLSHINA_MATRASA",
			16 => "PRUZINNIY",
			17 => "ZOSKOST",
			18 => "TIP_OBIVKI",
			19 => "MATERIAL",
			20 => "STIL_342",
			21 => "SROK_222",
			22 => "PROIZ_111",
			23 => "FASADI_111",
			24 => "PROP_159",
			25 => "PROP_284",
			26 => "PROP_2091",
			27 => "PROP_307",
			28 => "VISOTA_111",
			29 => "GLUB_111",
			30 => "PROP_335",
			31 => "ZOSKOST_111",
			32 => "TIP_OBIVKI_111",
			33 => "STOLESH_222",
			34 => "PROP_2065",
			35 => "PROP_305",
			36 => "PROP_352",
			37 => "PROP_317",
			38 => "PROP_357",
			39 => "PROP_2102",
			40 => "PROP_318",
			41 => "PROP_349",
			42 => "PROP_327",
			43 => "PROP_2052",
			44 => "PROP_370",
			45 => "PROP_336",
			46 => "PROP_2115",
			47 => "PROP_346",
			48 => "PROP_2120",
			49 => "PROP_2053",
			50 => "PROP_363",
			51 => "PROP_320",
			52 => "PROP_2089",
			53 => "PROP_325",
			54 => "PROP_2103",
			55 => "PROP_2085",
			56 => "PROP_300",
			57 => "PROP_322",
			58 => "PROP_362",
			59 => "PROP_365",
			60 => "PROP_359",
			61 => "PROP_364",
			62 => "PROP_356",
			63 => "PROP_343",
			64 => "PROP_2083",
			65 => "PROP_314",
			66 => "PROP_348",
			67 => "PROP_316",
			68 => "PROP_350",
			69 => "PROP_333",
			70 => "PROP_332",
			71 => "PROP_360",
			72 => "PROP_353",
			73 => "PROP_347",
			74 => "PROP_25",
			75 => "PROP_2114",
			76 => "PROP_301",
			77 => "PROP_2101",
			78 => "PROP_2067",
			79 => "PROP_323",
			80 => "PROP_324",
			81 => "PROP_355",
			82 => "PROP_304",
			83 => "PROP_358",
			84 => "PROP_319",
			85 => "PROP_344",
			86 => "PROP_328",
			87 => "PROP_338",
			88 => "PROP_2113",
			89 => "PROP_366",
			90 => "PROP_302",
			91 => "PROP_303",
			92 => "PROP_2054",
			93 => "PROP_341",
			94 => "PROP_223",
			95 => "PROP_283",
			96 => "PROP_354",
			97 => "PROP_313",
			98 => "PROP_2066",
			99 => "PROP_329",
			100 => "PROP_342",
			101 => "PROP_367",
			102 => "PROP_2084",
			103 => "PROP_340",
			104 => "PROP_351",
			105 => "PROP_368",
			106 => "PROP_369",
			107 => "PROP_331",
			108 => "PROP_337",
			109 => "PROP_345",
			110 => "PROP_339",
			111 => "PROP_310",
			112 => "PROP_309",
			113 => "PROP_330",
			114 => "PROP_2017",
			115 => "PROP_321",
			116 => "PROP_308",
			117 => "PROP_206",
			118 => "PROP_334",
			119 => "PROP_2100",
			120 => "PROP_311",
			121 => "PROP_2132",
			122 => "SHUM",
			123 => "PROP_361",
			124 => "PROP_326",
			125 => "PROP_2026",
			126 => "PROP_2027",
			127 => "PROP_2098",
			128 => "PROP_2122",
			129 => "PROP_24",
			130 => "PROP_2049",
			131 => "PROP_22",
			132 => "PROP_2095",
			133 => "PROP_2044",
			134 => "PROP_162",
			135 => "PROP_2055",
			136 => "PROP_2069",
			137 => "PROP_2062",
			138 => "PROP_2061",
			139 => "CML2_LINK",
			140 => "",
		),
		"INCLUDE_SUBSECTIONS" => "N",	// Показывать элементы подразделов раздела
		"LIST_META_KEYWORDS" => "-",	// Установить ключевые слова страницы из свойства раздела
		"LIST_META_DESCRIPTION" => "-",	// Установить описание страницы из свойства раздела
		"LIST_BROWSER_TITLE" => "-",	// Установить заголовок окна браузера из свойства раздела
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "CML2_LINK",
			2 => "DETAIL_PAGE_URL",
			3 => "",
		),
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "ARTICLE",
			1 => "POPUP_VIDEO",
			2 => "MORE_PHOTO",
			3 => "COLOR_REF",
			4 => "RAZMER",
			5 => "SIZES",
			6 => "SIZES2",
			7 => "VOLUME",
			8 => "SIZES3",
			9 => "SIZES4",
			10 => "SIZES5",
			11 => "SPORT",
			12 => "",
		),
		"LIST_OFFERS_LIMIT" => "10",
		"SORT_BUTTONS" => array(	// Кнопки сортировки
			0 => "POPULARITY",
			1 => "NAME",
			2 => "PRICE",
		),
		"SORT_PRICES" => "REGION_PRICE",	// Сортировка по цене
		"DEFAULT_LIST_TEMPLATE" => "block",	// Показывать товары в разделе по умолчанию
		"SECTION_DISPLAY_PROPERTY" => "",	// Свойство раздела с шаблоном по умолчанию
		"LIST_DISPLAY_POPUP_IMAGE" => "Y",	// Показывать всплывающее фото товара в шаблоне "Таблицей"
		"SECTION_PREVIEW_PROPERTY" => "DESCRIPTION",	// Брать описание из
		"SHOW_SECTION_PICTURES" => "Y",	// Показывать картинки подразделов
		"SHOW_SECTION_SIBLINGS" => "Y",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "HIT",
			1 => "BRAND",
			2 => "PROP_315",
			3 => "YM_ELEMENT_ID",
			4 => "EXPANDABLES_FILTER",
			5 => "LINK_SALE",
			6 => "EXTENDED_REVIEWS_COUNT",
			7 => "ASSOCIATED_FILTER",
			8 => "EXTENDED_REVIEWS_RAITING",
			9 => "PRODUCT_SET_GROUP",
			10 => "EXPANDABLES",
			11 => "CML2_ARTICLE",
			12 => "LINK_VACANCY",
			13 => "VIDEO_YOUTUBE",
			14 => "POPUP_VIDEO",
			15 => "PROP_2104",
			16 => "BLOG_COMMENTS_CNT",
			17 => "FORUM_MESSAGE_CNT",
			18 => "vote_count",
			19 => "LINK_NEWS",
			20 => "PODBORKI",
			21 => "ASSOCIATED",
			22 => "HELP_TEXT",
			23 => "rating",
			24 => "CML2_TRAITS",
			25 => "LINK_STAFF",
			26 => "CML2_TAXES",
			27 => "LINK_BLOG",
			28 => "vote_sum",
			29 => "SALE_TEXT",
			30 => "FORUM_TOPIC_ID",
			31 => "PROP_2033",
			32 => "FAVORIT_ITEM",
			33 => "SERVICES",
			34 => "CML2_ATTRIBUTES",
			35 => "COLOR_REF2",
			36 => "STIL",
			37 => "STOLESHNICA_MAT",
			38 => "SROK",
			39 => "GARANTIYA",
			40 => "PROIZVODITEL",
			41 => "FASADI",
			42 => "KORPUS",
			43 => "VESS",
			44 => "KOMPLECTACIA",
			45 => "DLINA",
			46 => "SHIRINA",
			47 => "VISOTA",
			48 => "GLUBINA",
			49 => "STOLESHNICA",
			50 => "MECHANIZM",
			51 => "FORMA_STOLA",
			52 => "PODEMNYI",
			53 => "ZERKALO",
			54 => "VISOTASIDENIA",
			55 => "REGULIROVKA",
			56 => "TOLSHINA_MATRASA",
			57 => "PRUZINNIY",
			58 => "ZOSKOST",
			59 => "TIP_OBIVKI",
			60 => "MATERIAL",
			61 => "SBORTIKOM",
			62 => "POL",
			63 => "CVETOVAYA",
			64 => "STIL_342",
			65 => "SROK_222",
			66 => "GARANTIYA_222",
			67 => "PROIZ_111",
			68 => "FASADI_111",
			69 => "PROP_159",
			70 => "PROP_284",
			71 => "PROP_2091",
			72 => "PROP_307",
			73 => "VISOTA_111",
			74 => "GLUB_111",
			75 => "STOLESH_111",
			76 => "KORPUS_111",
			77 => "MECHANIZM_111",
			78 => "FORM_111",
			79 => "PODEMNYI_111",
			80 => "ZERKALO_111",
			81 => "PROP_335",
			82 => "STOLESH_222",
			83 => "PROP_2065",
			84 => "PROP_305",
			85 => "PROP_352",
			86 => "PROP_317",
			87 => "PROP_357",
			88 => "PROP_2102",
			89 => "PROP_318",
			90 => "PROP_349",
			91 => "PROP_327",
			92 => "PROP_2052",
			93 => "PROP_370",
			94 => "PROP_336",
			95 => "PROP_2115",
			96 => "PROP_346",
			97 => "PROP_2120",
			98 => "PROP_2053",
			99 => "PROP_363",
			100 => "PROP_320",
			101 => "PROP_2089",
			102 => "PROP_325",
			103 => "PROP_2103",
			104 => "PROP_2085",
			105 => "PROP_300",
			106 => "PROP_322",
			107 => "PROP_362",
			108 => "PROP_365",
			109 => "PROP_359",
			110 => "PROP_364",
			111 => "PROP_356",
			112 => "PROP_343",
			113 => "PROP_2083",
			114 => "PROP_314",
			115 => "PROP_348",
			116 => "PROP_316",
			117 => "PROP_350",
			118 => "PROP_333",
			119 => "PROP_332",
			120 => "PROP_360",
			121 => "PROP_353",
			122 => "PROP_347",
			123 => "PROP_25",
			124 => "PROP_2114",
			125 => "PROP_301",
			126 => "PROP_2101",
			127 => "PROP_2067",
			128 => "PROP_323",
			129 => "PROP_324",
			130 => "PROP_355",
			131 => "PROP_304",
			132 => "PROP_358",
			133 => "PROP_319",
			134 => "PROP_344",
			135 => "PROP_328",
			136 => "PROP_338",
			137 => "PROP_2113",
			138 => "PROP_366",
			139 => "PROP_302",
			140 => "PROP_303",
			141 => "PROP_2054",
			142 => "PROP_341",
			143 => "PROP_223",
			144 => "PROP_283",
			145 => "PROP_354",
			146 => "PROP_313",
			147 => "PROP_2066",
			148 => "PROP_329",
			149 => "PROP_342",
			150 => "PROP_367",
			151 => "PROP_2084",
			152 => "PROP_340",
			153 => "PROP_351",
			154 => "PROP_368",
			155 => "PROP_369",
			156 => "PROP_331",
			157 => "PROP_337",
			158 => "PROP_345",
			159 => "PROP_339",
			160 => "PROP_310",
			161 => "PROP_309",
			162 => "PROP_330",
			163 => "PROP_2017",
			164 => "PROP_321",
			165 => "PROP_308",
			166 => "PROP_206",
			167 => "PROP_334",
			168 => "PROP_2100",
			169 => "PROP_311",
			170 => "PROP_2132",
			171 => "SHUM",
			172 => "PROP_361",
			173 => "PROP_326",
			174 => "PROP_2026",
			175 => "PROP_2090",
			176 => "PROP_2027",
			177 => "PROP_2098",
			178 => "PROP_2112",
			179 => "PROP_2122",
			180 => "PROP_221",
			181 => "PROP_24",
			182 => "PROP_2134",
			183 => "PROP_23",
			184 => "PROP_2049",
			185 => "PROP_22",
			186 => "PROP_2095",
			187 => "PROP_2044",
			188 => "PROP_162",
			189 => "PROP_207",
			190 => "PROP_220",
			191 => "PROP_2094",
			192 => "PROP_2092",
			193 => "PROP_2111",
			194 => "PROP_2133",
			195 => "PROP_2096",
			196 => "PROP_2086",
			197 => "PROP_285",
			198 => "PROP_2130",
			199 => "PROP_286",
			200 => "PROP_222",
			201 => "PROP_2121",
			202 => "PROP_2123",
			203 => "PROP_2124",
			204 => "PROP_2093",
			205 => "LINK_REVIEWS",
			206 => "PROP_312",
			207 => "PROP_3083",
			208 => "PROP_2055",
			209 => "PROP_2069",
			210 => "PROP_2062",
			211 => "PROP_2061",
			212 => "RECOMMEND",
			213 => "NEW",
			214 => "STOCK",
			215 => "VIDEO",
			216 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",	// Установить ключевые слова страницы из свойства
		"DETAIL_META_DESCRIPTION" => "-",	// Установить описание страницы из свойства
		"DETAIL_BROWSER_TITLE" => "-",	// Установить заголовок окна браузера из свойства
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "DETAIL_TEXT",
			4 => "DETAIL_PICTURE",
			5 => "DETAIL_PAGE_URL",
			6 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "ARTICLE",
			1 => "COLOR_REF",
			2 => "RAZMER",
			3 => "SIZES",
			4 => "WEIGHT",
			5 => "AGE",
			6 => "SIZES2",
			7 => "RUKAV",
			8 => "FRCOLLECTION",
			9 => "FRLINE",
			10 => "VOLUME",
			11 => "FRMADEIN",
			12 => "FRELITE",
			13 => "SIZES3",
			14 => "SIZES4",
			15 => "SIZES5",
			16 => "TALL",
			17 => "FRTYPE",
			18 => "FRAROMA",
			19 => "SPORT",
			20 => "VLAGOOTVOD",
			21 => "KAPUSHON",
			22 => "FRFITIL",
			23 => "FRFAMILY",
			24 => "FRSOSTAVCANDLE",
			25 => "FRFORM",
			26 => "",
		),
		"PROPERTIES_DISPLAY_LOCATION" => "DESCRIPTION",	// Показывать свойства товара
		"SHOW_BRAND_PICTURE" => "Y",	// Показывать логотип бренда
		"SHOW_ASK_BLOCK" => "Y",	// Показывать блок 'Задать вопрос'
		"ASK_FORM_ID" => "2",	// ID формы 'Задать вопрос'
		"SHOW_ADDITIONAL_TAB" => "Y",	// Показывать вкладку 'Дополнительно'
		"PROPERTIES_DISPLAY_TYPE" => "TABLE",	// Показывать свойства
		"SHOW_KIT_PARTS" => "Y",	// Показывать состав комплектов
		"SHOW_KIT_PARTS_PRICES" => "Y",	// Показывать цены частей комплекта
		"LINK_IBLOCK_TYPE" => "aspro_max_content",	// Тип инфоблока, элементы которого связаны с текущим элементом
		"LINK_IBLOCK_ID" => "32",	// ID инфоблока, элементы которого связаны с текущим элементом
		"LINK_PROPERTY_SID" => "",	// Свойство, в котором хранится связь
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",	// URL на страницу, где будет показан список связанных элементов
		"USE_ALSO_BUY" => "Y",	// Показывать блок "С этим товаром покупают"
		"ALSO_BUY_ELEMENT_COUNT" => "5",	// Количество элементов для отображения
		"ALSO_BUY_MIN_BUYES" => "2",	// Минимальное количество покупок товара
		"USE_STORE" => "Y",	// Показывать блок "Количество товара на складе"
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "Y",
		"USE_MIN_AMOUNT" => "N",	// Показывать вместо точного количества информацию о достаточности
		"MIN_AMOUNT" => "10",
		"STORE_PATH" => "/contacts/stores/#store_id#/",	// Шаблон пути к каталогу STORE (относительно корня)
		"MAIN_TITLE" => "Наличие на складах",	// Заголовок блока
		"MAX_AMOUNT" => "20",
		"USE_ONLY_MAX_AMOUNT" => "Y",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "sort",
		"OFFERS_SORT_ORDER2" => "asc",
		"PAGER_TEMPLATE" => "main",	// Шаблон постраничной навигации
		"DISPLAY_TOP_PAGER" => "N",	// Выводить над списком
		"DISPLAY_BOTTOM_PAGER" => "Y",	// Выводить под списком
		"PAGER_TITLE" => "Товары",	// Название категорий
		"PAGER_SHOW_ALWAYS" => "N",	// Выводить всегда
		"PAGER_DESC_NUMBERING" => "N",	// Использовать обратную навигацию
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",	// Время кеширования страниц для обратной навигации
		"PAGER_SHOW_ALL" => "N",	// Показывать ссылку "Все"
		"IBLOCK_STOCK_ID" => "24",	// ID инфоблока акций
		"IBLOCK_LINK_NEWS_ID" => "23",	// ID инфоблока новостей
		"IBLOCK_SERVICES_ID" => "25",	// ID инфоблока услуг
		"IBLOCK_TIZERS_ID" => "12",	// ID инфоблока тизеров
		"IBLOCK_LINK_REVIEWS_ID" => "21",	// ID инфоблока отзывов
		"STAFF_IBLOCK_ID" => "18",	// ID инфоблока сотрудников
		"VACANCY_IBLOCK_ID" => "2",	// ID инфоблока вакансий
		"SHOW_QUANTITY" => "Y",
		"SHOW_MEASURE" => "N",	// Показывать единицы измерения
		"SHOW_QUANTITY_COUNT" => "Y",
		"USE_RATING" => "Y",	// Использовать рейтинг
		"DISPLAY_WISH_BUTTONS" => "Y",
		"DEFAULT_COUNT" => "1",	// Количество, добавляемое в корзину по умолчанию
		"SHOW_HINTS" => "Y",	// Показывать подсказки у свойств
		"AJAX_OPTION_ADDITIONAL" => "",	// Дополнительный идентификатор
		"ADD_SECTIONS_CHAIN" => "Y",	// Включать раздел в цепочку навигации
		"ADD_ELEMENT_CHAIN" => "Y",	// Включать название элемента в цепочку навигации
		"ADD_PROPERTIES_TO_BASKET" => "Y",	// Добавлять в корзину свойства товаров и предложений
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",	// Разрешить добавлять в корзину товары, у которых заполнены не все характеристики
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",	// Использовать код группы из переменной, если не задан раздел элемента
		"STORES" => array(	// Склады
			0 => "",
			1 => "",
		),
		"USER_FIELDS" => array(	// Пользовательские поля
			0 => "",
			1 => "UF_CATALOG_ICON",
			2 => "",
		),
		"FIELDS" => array(	// Поля
			0 => "",
			1 => "",
		),
		"SHOW_EMPTY_STORE" => "Y",	// Отображать склад при отсутствии на нем товара
		"SHOW_GENERAL_STORE_INFORMATION" => "N",	// Показывать общую информацию по складам
		"TOP_ELEMENT_COUNT" => "8",	// Количество выводимых элементов
		"TOP_LINE_ELEMENT_COUNT" => "4",	// Количество элементов, выводимых в одной строке таблицы
		"TOP_ELEMENT_SORT_FIELD" => "sort",	// По какому полю сортируем товары в разделе
		"TOP_ELEMENT_SORT_ORDER" => "asc",	// Порядок сортировки товаров в разделе
		"TOP_ELEMENT_SORT_FIELD2" => "sort",	// Поле для второй сортировки товаров в разделе
		"TOP_ELEMENT_SORT_ORDER2" => "asc",	// Порядок второй сортировки товаров в разделе
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPONENT_TEMPLATE" => "main",
		"DETAIL_SET_CANONICAL_URL" => "Y",	// Устанавливать канонический URL
		"SHOW_DEACTIVATED" => "N",	// Показывать деактивированные товары
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "",
		),
		"TOP_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_LIMIT" => "10",
		"SECTION_TOP_BLOCK_TITLE" => "Лучшие предложения",	// Заголовок блока
		"OFFER_TREE_PROPS" => array(
			0 => "COLOR_REF",
			1 => "RAZMER",
		),
		"USE_BIG_DATA" => "Y",	// Показывать персональные рекомендации
		"BIG_DATA_RCM_TYPE" => "similar",	// Тип рекомендации
		"SHOW_DISCOUNT_PERCENT" => "Y",	// Показывать экономию
		"SHOW_OLD_PRICE" => "Y",	// Показывать старую цену
		"VIEWED_ELEMENT_COUNT" => "20",
		"VIEWED_BLOCK_TITLE" => "Ранее вы смотрели",
		"ELEMENT_SORT_FIELD_BOX" => "name",
		"ELEMENT_SORT_ORDER_BOX" => "asc",
		"ELEMENT_SORT_FIELD_BOX2" => "id",
		"ELEMENT_SORT_ORDER_BOX2" => "desc",
		"ADD_PICT_PROP" => "MORE_PHOTO",	// Дополнительная картинка основного товара
		"OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
		"MAX_GALLERY_ITEMS" => "5",	// Количество картинок в галерее
		"SHOW_GALLERY" => "Y",	// Отображать галерею
		"SHOW_PROPS" => "Y",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "Y",	// Добавлять детальную картинку в слайдер
		"SKU_DETAIL_ID" => "oid",	// Параметр определяющий SKU на детальной
		"USE_MAIN_ELEMENT_SECTION" => "Y",	// Использовать основной раздел для показа элемента
		"SET_LAST_MODIFIED" => "Y",	// Устанавливать в заголовках ответа время модификации страницы
		"PAGER_BASE_LINK_ENABLE" => "N",	// Включить обработку ссылок
		"SHOW_404" => "Y",	// Показ специальной страницы
		"MESSAGE_404" => "",
		"AJAX_FILTER_CATALOG" => "Y",	// Использовать ajax фильтр
		"AJAX_CONTROLS" => "Y",	// Ajax смена сортировки и видов отображения
		"SECTION_BACKGROUND_IMAGE" => "-",	// Установить фоновую картинку для шаблона из свойства
		"DETAIL_BACKGROUND_IMAGE" => "-",	// Установить фоновую картинку для шаблона из свойства
		"DISPLAY_ELEMENT_SLIDER" => "10",	// Количество элементов в слайдерах
		"SHOW_ONE_CLICK_BUY" => "Y",	// Отображать кнопку "Покупка в 1 клик" в карточке товара
		"USE_GIFTS_DETAIL" => "Y",	// Показывать блок "Подарки" в детальном просмотре
		"USE_GIFTS_SECTION" => "Y",	// Показывать блок "Подарки" в списке
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",	// Показывать блок "Товары к подарку" в детальном просмотре
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "8",	// Количество элементов в блоке "Подарки" в строке в детальном просмотре
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",	// Скрыть заголовок "Подарки" в детальном просмотре
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",	// Текст заголовка "Подарки" в детальном просмотре
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",	// Текст метки "Подарка" в детальном просмотре
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "3",	// Количество элементов в блоке "Подарки" строке в списке
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",	// Скрыть заголовок "Подарки" в списке
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",	// Текст заголовка "Подарки" в списке
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",	// Текст метки "Подарка" в списке
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",	// Показывать процент скидки
		"GIFTS_SHOW_OLD_PRICE" => "Y",	// Показывать старую цену
		"GIFTS_SHOW_NAME" => "Y",	// Показывать название
		"GIFTS_SHOW_IMAGE" => "Y",	// Показывать изображение
		"GIFTS_MESS_BTN_BUY" => "Выбрать",	// Текст кнопки "Выбрать"
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",	// Количество элементов в блоке "Товары к подарку" в строке в детальном просмотре
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",	// Скрыть заголовок "Товары к подарку" в детальном просмотре
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",	// Текст заголовка "Товары к подарку"
		"OFFER_HIDE_NAME_PROPS" => "N",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",	// Не подключать js-библиотеки в компоненте
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",	// Включить сохранение информации о просмотре товара на детальной странице для старых шаблонов
		"SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SECTIONS_LIST_PREVIEW_DESCRIPTION" => "Y",	// Показывать описание подразделов
		"SALE_STIKER" => "SALE_TEXT",	// Свойство со стикером акций
		"SHOW_DISCOUNT_TIME" => "Y",	// Отображать срок действия скидки
		"SHOW_RATING" => "Y",	// Отображать рейтинг
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_OFFERS_LIMIT" => "0",	// Максимальное количество предложений для показа (0 - все)
		"DETAIL_EXPANDABLES_TITLE" => "С этим товаром покупают",	// Заголовок блока "Аксессуары"
		"DETAIL_ASSOCIATED_TITLE" => "Вам также может понравиться",	// Заголовок блока "Похожие товары"
		"DETAIL_LINKED_GOODS_SLIDER" => "Y",	// Отображать связанные товары слайдером
		"DETAIL_LINKED_GOODS_TABS" => "Y",	// Отображать связанные товары по табам
		"DETAIL_PICTURE_MODE" => "MAGNIFIER",
		"SHOW_UNABLE_SKU_PROPS" => "Y",	// Отображать недоступные значения свойств для ТП
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",	// Недоступные торговые предложения
		"DETAIL_STRICT_SECTION_CHECK" => "N",	// Строгая проверка раздела для детального показа элемента
		"COMPATIBLE_MODE" => "Y",	// Включить режим совместимости
		"TEMPLATE_THEME" => "blue",
		"LABEL_PROP" => "",
		"PRODUCT_DISPLAY_MODE" => "Y",
		"COMMON_SHOW_CLOSE_POPUP" => "N",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"SHOW_MAX_QUANTITY" => "N",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"SIDEBAR_SECTION_SHOW" => "Y",
		"SIDEBAR_DETAIL_SHOW" => "N",
		"SIDEBAR_PATH" => "",
		"USE_SALE_BESTSELLERS" => "Y",
		"FILTER_VIEW_MODE" => "VERTICAL",
		"FILTER_HIDE_ON_MOBILE" => "N",
		"INSTANT_RELOAD" => "N",
		"COMPARE_POSITION_FIXED" => "Y",
		"COMPARE_POSITION" => "top left",
		"USE_RATIO_IN_RANGES" => "Y",
		"USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
		"COMMON_ADD_TO_BASKET_ACTION" => "ADD",
		"TOP_ADD_TO_BASKET_ACTION" => "ADD",
		"SECTION_ADD_TO_BASKET_ACTION" => "ADD",
		"DETAIL_ADD_TO_BASKET_ACTION" => array(
			0 => "BUY",
		),
		"DETAIL_ADD_TO_BASKET_ACTION_PRIMARY" => array(
			0 => "BUY",
		),
		"TOP_PROPERTY_CODE_MOBILE" => "",
		"TOP_VIEW_MODE" => "SECTION",
		"TOP_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons,compare",
		"TOP_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false}]",
		"TOP_ENLARGE_PRODUCT" => "STRICT",
		"TOP_SHOW_SLIDER" => "Y",
		"TOP_SLIDER_INTERVAL" => "3000",
		"TOP_SLIDER_PROGRESS" => "N",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"LIST_PROPERTY_CODE_MOBILE" => "",
		"LIST_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons,compare",
		"LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false}]",
		"LIST_ENLARGE_PRODUCT" => "STRICT",
		"LIST_SHOW_SLIDER" => "Y",
		"LIST_SLIDER_INTERVAL" => "3000",
		"LIST_SLIDER_PROGRESS" => "N",
		"DETAIL_MAIN_BLOCK_PROPERTY_CODE" => "",
		"DETAIL_MAIN_BLOCK_OFFERS_PROPERTY_CODE" => "",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_BRAND_USE" => "N",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_IMAGE_RESOLUTION" => "16by9",
		"DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
		"DETAIL_PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
		"DETAIL_BLOCKS_ORDER" => "complect,nabor,offers,modules,tabs,gifts,services,news,blog,staff,vacancy,goods",	// Порядок отображения блоков (с табами)
		"DETAIL_SHOW_SLIDER" => "N",
		"DETAIL_DETAIL_PICTURE_MODE" => array(
			0 => "POPUP",
			1 => "MAGNIFIER",
		),
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"MESS_PRICE_RANGES_TITLE" => "Цены",
		"MESS_DESCRIPTION_TAB" => "Описание",
		"MESS_PROPERTIES_TAB" => "Характеристики",
		"MESS_COMMENTS_TAB" => "Комментарии",
		"LAZY_LOAD" => "N",
		"LOAD_ON_SCROLL" => "N",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"DETAIL_DOCS_PROP" => "-",	// Свойство с "Документами"
		"STIKERS_PROP" => "HIT",	// Свойство со стикерами
		"USE_SHARE" => "Y",	// Показывать блок "Поделиться"
		"TAB_OFFERS_NAME" => "",	// Заголовок блока "Цены"
		"TAB_DESCR_NAME" => "",	// Заголовок блока "Описание"
		"TAB_KOMPLECT_NAME" => "",	// Заголовок блока "Состав комплекта"
		"TAB_NABOR_NAME" => "",	// Заголовок блока "Купить набор"
		"TAB_CHAR_NAME" => "",	// Заголовок блока "Характеристики"
		"TAB_VIDEO_NAME" => "",	// Заголовок блока "Видео"
		"TAB_REVIEW_NAME" => "",	// Заголовок блока "Отзывы"
		"TAB_FAQ_NAME" => "",
		"TAB_STOCK_NAME" => "",	// Заголовок блока "Наличие"
		"TAB_DOPS_NAME" => "",	// Заголовок блока "Дополнительно"
		"BLOCK_SERVICES_NAME" => "",	// Заголовок блока "Услуги"
		"BLOCK_DOCS_NAME" => "",	// Заголовок блока "Документы"
		"DIR_PARAMS" => CMax::GetDirMenuParametrs(__DIR__),
		"ELEMENT_DETAIL_TYPE_VIEW" => "FROM_MODULE",
		"SHOW_CHEAPER_FORM" => "Y",	// Показывать форму "Нашли дешевле"
		"LANDING_TITLE" => "Популярные категории",	// Заголовок блока "Популярные категории" для посадочных страниц
		"LANDING_SECTION_COUNT" => "10",	// Количество видимых элементов в блоке "Популярные категории" для посадочных страниц (>768px)
		"LANDING_SEARCH_TITLE" => "Похожие запросы",	// Заголовок блока "Похожие запросы" для посадочных страниц в поиске
		"LANDING_SEARCH_COUNT" => "7",	// Количество видимых элементов в блоке "Похожие запросы" для посадочных страниц в поиске (>768px)
		"LIST_SECTIONS_TYPE_VIEW" => "sections_1",
		"LIST_ELEMENTS_TYPE_VIEW" => "list_elements_1",
		"CHEAPER_FORM_NAME" => "",	// Текст ссылки "Нашли дешевле"
		"SECTIONS_TYPE_VIEW" => "FROM_MODULE",	// Шаблон страницы блока списка разделов
		"SECTION_ELEMENTS_TYPE_VIEW" => "list_elements_1",	// Шаблон страницы блока списка элементов
		"ELEMENT_TYPE_VIEW" => "FROM_MODULE",	// Шаблон страницы блока детальной страницы
		"LANDING_TYPE_VIEW" => "FROM_MODULE",	// Шаблон страницы блока  "Популярные категории"
		"FILE_404" => "",	// Страница для показа (по умолчанию /404.php)
		"SHOW_MEASURE_WITH_RATIO" => "N",	// Выводить единицу измерения с коэффициентом при отображении минимальной цены для товаров с торговыми предложениями
		"SHOW_COUNTER_LIST" => "Y",	// Отображать срок действия скидки в списке
		"SHOW_DISCOUNT_TIME_EACH_SKU" => "N",	// Отображать срок действия скидки для каждого торгового предложения
		"USER_CONSENT" => "N",	// Запрашивать согласие
		"USER_CONSENT_ID" => "0",	// Соглашение
		"USER_CONSENT_IS_CHECKED" => "Y",	// Галка по умолчанию проставлена
		"USER_CONSENT_IS_LOADED" => "N",	// Загружать текст сразу
		"SHOW_ARTICLE_SKU" => "Y",	// Отображать артикул товара, если у ТП нет своего значения артикула
		"USE_FILTER_PRICE" => "N",	// Использовать цену для фильтра
		"DISPLAY_ELEMENT_COUNT" => "Y",	// Отображать количество элементов у свойств в фильтре
		"RESTART" => "N",	// Искать без учета морфологии (при отсутствии результата поиска)
		"USE_LANGUAGE_GUESS" => "Y",	// Включить автоопределение раскладки клавиатуры)
		"NO_WORD_LOGIC" => "Y",	// Отключить обработку слов как логических операторов
		"SORT_REGION_PRICE" => "BASE",	// Цена для сортировки в регионе по умолчанию
		"SHOW_SECTION_DESC" => "Y",	// Показывать описание раздела
		"USE_ADDITIONAL_GALLERY" => "Y",	// Отображать блок "Фотогалерея"
		"ADDITIONAL_GALLERY_TYPE" => "BIG",	// Тип блока "Фотогалерея"
		"ADDITIONAL_GALLERY_PROPERTY_CODE" => "-",	// Cвойство с "Фотогалереей"
		"ADDITIONAL_GALLERY_OFFERS_PROPERTY_CODE" => "",	// Свойство торговых предложений с "Фотогалереей"
		"BLOCK_ADDITIONAL_GALLERY_NAME" => "",	// Заголовок блока "Фотогалерея"
		"STORES_FILTER" => "TITLE",	// Сортировка складов
		"STORES_FILTER_ORDER" => "SORT_ASC",	// Направление сортировки
		"VIEW_BLOCK_TYPE" => "N",
		"SHOW_HOW_BUY" => "Y",	// Отображать таб "Как купить"
		"TITLE_HOW_BUY" => "Как купить",	// Заголовок таба "Как купить"
		"SHOW_DELIVERY" => "Y",	// Отображать таб "Доставка"
		"TITLE_DELIVERY" => "Доставка",	// Заголовок таба "Доставка"
		"SHOW_PAYMENT" => "Y",	// Отображать таб "Оплата"
		"TITLE_PAYMENT" => "Оплата",	// Заголовок таба "Оплата"
		"SHOW_GARANTY" => "Y",	// Отображать блок "Условия гарантии" в детальной карточке тип5
		"TITLE_GARANTY" => "Условия гарантии",	// Заголовок блока "Условия гарантии"
		"TITLE_SLIDER" => "Рекомендуем",	// Заголовок блока с персональными рекомендациями
		"SHOW_SEND_GIFT" => "Y",	// Показывать форму "Хочу в подарок"
		"SEND_GIFT_FORM_NAME" => "",	// Текст ссылки "Хочу в подарок"
		"BLOCK_LANDINGS_NAME" => "",
		"BLOG_IBLOCK_ID" => "22",	// ID инфоблока статьи
		"BLOCK_BLOG_NAME" => "",	// Заголовок блока "Полезное"
		"RECOMEND_COUNT" => "5",	// Количество элементов в блоке "Рекомендуем"
		"VISIBLE_PROP_COUNT" => "6",	// Количество свойств сверху
		"BIGDATA_EXT" => "bigdata_1",	// Шаблон персональных рекомендаций для детальной страницы каталога справа
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "Y",	// Показывать процент экономии
		"ALT_TITLE_GET" => "NORMAL",	// Брать alt и title для картинок из
		"BUNDLE_ITEMS_COUNT" => "3",	// Количество отображаемых товаров в наборе
		"SHOW_LANDINGS_SEARCH" => "Y",	// Отображать блок "Похожие запросы"
		"SHOW_LANDINGS" => "Y",	// Отображать блок "Популярные категории"
		"LANDING_POSITION" => "BEFORE_PRODUCTS",	// Расположение блока "Популярные категории"
		"USE_DETAIL_PREDICTION" => "Y",	// Использовать предсказания скидок
		"SECTION_BG" => "-",	// Свойство с фоновой картинкой у раздела
		"OFFER_SHOW_PREVIEW_PICTURE_PROPS" => "",
		"LANDING_IBLOCK_ID" => "31",	// ИД инфоблока посадочных страниц
		"DETAIL_BLOCKS_TAB_ORDER" => "desc,char,stores,video,reviews,buy,payment,delivery,custom_tab",	// Порядок отображения блоков в табах
		"DETAIL_BLOCKS_ALL_ORDER" => "complect,goods,nabor,offers,modules,desc,char,buy,payment,delivery,video,stores,custom_tab,services,news,blog,reviews,staff,vacancy,gifts",	// Порядок отображения блоков (без табов)
		"DELIVERY_CALC" => "Y",
		"DELIVERY_CALC_NAME" => "",
		"ASK_TAB" => "",	// Заголовок кнопки "Задать вопрос"
		"TAB_NEWS_NAME" => "",	// Заголовок блока "Новости"
		"TAB_STAFF_NAME" => "",	// Заголовок блока "Сотрудники"
		"TAB_VACANCY_NAME" => "",	// Заголовок блока "Вакансии"
		"STAFF_VIEW_TYPE" => "staff_block",	// Вид отображения сотрудников
		"SECTION_TYPE_VIEW" => "FROM_MODULE",	// Шаблон страницы блока списка подразделов
		"SHOW_BUY_DELIVERY" => "Y",	// Отображать блок "Оплата и доставка" в детальной карточке тип5
		"TITLE_BUY_DELIVERY" => "Оплата и доставка",	// Заголовок блока "Оплата и доставка"
		"BLOG_URL" => "catalog_comments",	// ID блога для расширенных отзывов
		"SHOW_MORE_SUBSECTIONS" => "Y",	// Показывать вложенные подразделы
		"SHOW_SIDE_BLOCK_LAST_LEVEL" => "Y",	// Показывать боковое меню в последнем подразделе каталога
		"SHOW_SORT_IN_FILTER" => "N",	// Отображать сортировку в блоке с фильтром при разрешении < 768px
		"SUBSECTION_PREVIEW_PROPERTY" => "DESCRIPTION",	// Брать описание для подразделов из
		"SHOW_SUBSECTION_DESC" => "Y",	// Показывать описание подразделов
		"USE_CUSTOM_RESIZE" => "N",	// Использовать ресайз картинок в галерее из настроек инфоблока
		"LINKED_ELEMENT_TAB_SORT_FIELD" => "sort",	// По какому полю сортируем связанные товары
		"LINKED_ELEMENT_TAB_SORT_ORDER" => "asc",	// Порядок сортировки связанные товары
		"LINKED_ELEMENT_TAB_SORT_FIELD2" => "id",	// Поле для второй сортировки связанные товары
		"LINKED_ELEMENT_TAB_SORT_ORDER2" => "desc",	// Порядок второй сортировки связанные товары
		"DETAIL_BLOG_EMAIL_NOTIFY" => "Y",	// Уведомление об отзыве по электронной почте
		"MAX_IMAGE_SIZE" => "0.5",	// Максимальный размер прикрепляемых картинок
		"BIGDATA_SHOW_FROM_SECTION" => "N",	// Показывать из текущего раздела
		"LANDING_SEARCH_COUNT_MOBILE" => "3",	// Количество видимых элементов в блоке "Похожие запросы" для посадочных страниц в поиске (<768px)
		"USE_BIG_DATA_IN_SEARCH" => "Y",	// Показывать персональные рекомендации при отсутствии результатов
		"BIG_DATA_IN_SEARCH_RCM_TYPE" => "bestsell",	// Тип рекомендации
		"TITLE_SLIDER_IN_SEARCH" => "Возможно, вам подойдет",	// Заголовок блока с персональными рекомендациями
		"RECOMEND_IN_SEARCH_COUNT" => "10",	// Количество элементов в блоке "Рекомендуем"
		"LANDING_SECTION_COUNT_MOBILE" => "3",	// Количество видимых элементов в блоке "Популярные категории" для посадочных страниц (<768px)
		"SHOW_SMARTSEO_TAGS" => "Y",	// Отображать облако тегов из Умного SEO
		"SMARTSEO_TAGS_COUNT" => "10",	// Количество видимых элементов в облаке тегов из Умного SEO (>768px)
		"SMARTSEO_TAGS_COUNT_MOBILE" => "3",	// Количество видимых элементов в облаке тегов из Умного SEO (<768px)
		"TAB_BUY_SERVICES_NAME" => "",	// Заголовок блока "Дополнительные услуги"
		"COUNT_SERVICES_IN_ANNOUNCE" => "2",	// Количество дополнительных услуг сверху
		"SHOW_ALL_SERVICES_IN_SLIDE" => "Y",	// Показывать остальные услуги в анонсе
		"DETAIL_SET_PRODUCT_TITLE" => "Собрать комплект",	// Заголовок блока "Модули"
		"DISPLAY_LINKED_PAGER" => "Y",	// Отображать кнопку показать еще для связанных товаров
		"MODULES_ELEMENT_COUNT" => "10",	// Количество элементов в блоке "Модули"
		"REVIEW_COMMENT_REQUIRED" => "N",	// Текст отзыва обязателен
		"REVIEW_FILTER_BUTTONS" => array(	// Кнопки фильтрации отзывов
			0 => "PHOTO",
			1 => "RATING",
			2 => "TEXT",
		),
		"REAL_CUSTOMER_TEXT" => "",	// Текст подписи «реальный покупатель»
		"USE_COMPARE_GROUP" => "N",	// Использовать группировку на странице сравнения
		"SHOW_SORT_RANK_BUTTON" => "Y",	// Выводить кнопку сортировки по релевантности
		"HIDE_SUBSECTIONS_LIST" => "N",	// Скрывать подразделы на странице списка товаров
		"USE_LANDINGS_GROUP" => "N",	// Группировать посадочные страницы
		"LANDINGS_GROUP_FROM_SEO" => "N",	// Брать названия групп посадочных страниц из SEO
		"SMARTSEO_TAGS_BY_GROUPS" => "N",	// Группировать элементы в облаке тегов из Умного SEO по условиям правил
		"SMARTSEO_TAGS_SHOW_DEACTIVATED" => "N",	// Отображать деактивированные элементы облака тегов из Умного SEO
		"SMARTSEO_TAGS_SORT" => "SORT",	// Поле сортировки элементов облака тегов из Умного SEO
		"SMARTSEO_TAGS_LIMIT" => "",	// Количество обрабатываемых тегов из Умного SEO
		"SHOW_SKU_DESCRIPTION" => "N",	// Отображать описание для каждого торгового предложения
		"DISPLAY_LINKED_ELEMENT_SLIDER_CROSSLINK" => "",	// Количество элементов получаемых для перекрестных продаж
		"SHOW_KIT_ALL" => "N",	// Загружать все товары комплекта сразу
		"VISIBLE_PROP_WITH_OFFER" => "N",	// Учитывать свойства торговых предложений при выводе свойств сверху
		"BIGDATA_EXT_BOTTOM" => "bigdata_bottom_1",	// Шаблон персональных рекомендаций для детальной страницы каталога снизу
		"BIGDATA_COUNT" => "5",	// Количество персональных рекомендаций
		"BIGDATA_TYPE_VIEW" => "FROM_MODULE",	// Вид персональных рекомендаций
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE_PATH#/#ELEMENT_ID#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>